<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="2" skipped="2">
  <reporter-output>
    <line>
      <![CDATA[my method 4 is running]]>
    </line>
    <line>
      <![CDATA[test case passed successfully]]>
    </line>
    <line>
      <![CDATA[Name of test method completed success ismyMethod4]]>
    </line>
    <line>
      <![CDATA[test case failed plz check again]]>
    </line>
    <line>
      <![CDATA[Name of test method failed ismyMethod5]]>
    </line>
    <line>
      <![CDATA[Test case skipped,please check dependent method]]>
    </line>
    <line>
      <![CDATA[Name of test method skipped ismyMethod6]]>
    </line>
    <line>
      <![CDATA[my method 1 is running]]>
    </line>
    <line>
      <![CDATA[test case passed successfully]]>
    </line>
    <line>
      <![CDATA[Name of test method completed success ismyMethod1]]>
    </line>
    <line>
      <![CDATA[test case failed plz check again]]>
    </line>
    <line>
      <![CDATA[Name of test method failed ismyMethod2]]>
    </line>
    <line>
      <![CDATA[Test case skipped,please check dependent method]]>
    </line>
    <line>
      <![CDATA[Name of test method skipped ismyMethod3]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-05T22:55:40 IST" name="Suite" finished-at="2022-07-05T22:55:40 IST" duration-ms="172">
    <groups>
    </groups>
    <test started-at="2022-07-05T22:55:40 IST" name="Test" finished-at="2022-07-05T22:55:40 IST" duration-ms="172">
      <class name="listener.myTest2">
        <test-method signature="myMethod4()[pri:0, instance:listener.myTest2@5fa07e12]" started-at="2022-07-05T22:55:40 IST" name="myMethod4" finished-at="2022-07-05T22:55:40 IST" duration-ms="19" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[my method 4 is running]]>
            </line>
            <line>
              <![CDATA[test case passed successfully]]>
            </line>
            <line>
              <![CDATA[Name of test method completed success ismyMethod4]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod4 -->
        <test-method signature="myMethod5()[pri:0, instance:listener.myTest2@5fa07e12]" started-at="2022-07-05T22:55:40 IST" name="myMethod5" finished-at="2022-07-05T22:55:40 IST" duration-ms="16" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listener.myTest2.myMethod5(myTest2.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test case failed plz check again]]>
            </line>
            <line>
              <![CDATA[Name of test method failed ismyMethod5]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod5 -->
        <test-method signature="myMethod6()[pri:0, instance:listener.myTest2@5fa07e12]" started-at="2022-07-05T22:55:40 IST" name="myMethod6" finished-at="2022-07-05T22:55:40 IST" depends-on-methods="listener.myTest2.myMethod5" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method myTest2.myMethod6()[pri:0, instance:listener.myTest2@5fa07e12] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method myTest2.myMethod6()[pri:0, instance:listener.myTest2@5fa07e12] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Test case skipped,please check dependent method]]>
            </line>
            <line>
              <![CDATA[Name of test method skipped ismyMethod6]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod6 -->
      </class> <!-- listener.myTest2 -->
      <class name="listener.myTest">
        <test-method signature="myMethod1()[pri:0, instance:listener.myTest@747edf66]" started-at="2022-07-05T22:55:40 IST" name="myMethod1" finished-at="2022-07-05T22:55:40 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[my method 1 is running]]>
            </line>
            <line>
              <![CDATA[test case passed successfully]]>
            </line>
            <line>
              <![CDATA[Name of test method completed success ismyMethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod1 -->
        <test-method signature="myMethod2()[pri:0, instance:listener.myTest@747edf66]" started-at="2022-07-05T22:55:40 IST" name="myMethod2" finished-at="2022-07-05T22:55:40 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listener.myTest.myMethod2(myTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test case failed plz check again]]>
            </line>
            <line>
              <![CDATA[Name of test method failed ismyMethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod2 -->
        <test-method signature="myMethod3()[pri:0, instance:listener.myTest@747edf66]" started-at="2022-07-05T22:55:40 IST" name="myMethod3" finished-at="2022-07-05T22:55:40 IST" depends-on-methods="listener.myTest.myMethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method myTest.myMethod3()[pri:0, instance:listener.myTest@747edf66] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method myTest.myMethod3()[pri:0, instance:listener.myTest@747edf66] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Test case skipped,please check dependent method]]>
            </line>
            <line>
              <![CDATA[Name of test method skipped ismyMethod3]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod3 -->
      </class> <!-- listener.myTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
